//= ../../node_modules/jquery/dist/jquery.min.js
// = lib/jquery-ui.min.js
//= lib/jquery.inputmask.min.js
//= ../../node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.js
//= lib/slick-1.8.1/slick.min.js
//= lib/allinone_carousel.min.js
// = lib/jquery.touchSwipe.min.js
// = lib/stickUp.js
// = lib/bootstrap-4.4.1/util.js
// = lib/bootstrap-4.4.1/scrollspy.js
// = lib/svgxuse.min.js
